title: Teddy Wahle
description: >- # this means to ignore newlines until "baseurl:"
  essays, ideas, book reviews, and project features
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: teddywahle
github_username:  theodorewahle

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
